baseURL = "https://samskeo.ch/"
capitalizeListTitles = false
disableHugoGeneratorInject = true
languageCode = "en-GB-oxendict"
pluralizeListTitles = false
title = "djscythe's website"
uglyURLs = true

[build]
noJSConfigInAssets = true

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]']]
inline = [['\(', '\)']]

[markup.goldmark.extensions.typographer]
apostrophe = "’"
ellipsis = "…"
emDash = "—"
enDash = "–"
leftAngleQuote = "«"
leftDoubleQuote = "“"
leftSingleQuote = "‘"
rightAngleQuote = "»"
rightDoubleQuote = "”"
rightSingleQuote = "’"

[markup.goldmark.parser.attribute]
block = true

[minify]
minifyOutput = true

[outputs]
home = ["html"]
taxonomy = ["html"]
term = ["html"]

[params]
displayTitle = "sam skeoch"

[params.author]
email = "me@samskeo.ch"
name = "sam skeoch"
